name: scpy_dev

channels:
    - conda-forge
    - spectrocat
    - defaults

dependencies:
    - python=3.8

    # specific
    - quadprog=0.1.9
    - brukeropusreader
    - quaternion
    - nmrglue

    # for the core package
    - colorama
    - dill
    - ipython
    - jinja2
    - matplotlib>=3.5
    - numba
    - numpy>=1.21.0
    - orderedset
    - pint=0.16.1
    - plotly
    - requests
    - scipy
    - tqdm
    - traitlets
    - traittypes
    - xlrd

    # example and test data
    - spectrochempy_data

    # mainly for install and a bit more...
    - setuptools
    - setuptools_scm
    - git

    # need this, because the API is mainly designed to run in Jupyter notebook
    - ipywidgets
    - ipympl
    - jupyterlab>=2.2.10
    - nodejs


    # DEV: just for testing
    - pytest
    - pytest-doctestplus
    - pytest-flake8
    - scikit-image
    - coverage
    - black
    - pre-commit

    # DEV: code and docs
    - mamba
    - jupytext
    - sphinx<4.0
    - sphinx_rtd_theme
    - autodocsumm
    - sphinx-gallery<=0.7.0
    - nbsphinx=0.8.1
    - jupyter_sphinx
    - json5
    - sphinx-copybutton
    - numpydoc
    - pandoc

    # DEV: build
    - conda-build
    - conda-verify
    - anaconda-client

    # optional
    # - xarray
    # - datashader
    # - scikit-learn

    - pip
    - pip:
        - autodoc_traits
