name: scpy

channels:
    - conda-forge
    - spectrocat
    - defaults

dependencies:
    # specific
    - quadprog
    - brukeropusreader
    - quaternion
    - nmrglue

    # for the core package
    - colorama
    - dill
    - ipython
    - jinja2
    - mamba
    - matplotlib-base
    - numpy
    - orderedset
    - pint
    - requests
    - scipy
    - tqdm
    - traitlets
    - traittypes

    # to be suppressed when code change is finished
    - xlrd

    # mainly for install and a bit more...
    - setuptools
    - setuptools_scm
    - git

    # need this, because the API is mainly designed to run in Jupyter notebook
    - ipywidgets
    - ipympl
    - jupyterlab
    - nodejs
