blank_issues_enabled: false
contact_links:
  - name: Usage question
    url: https://github.com/spectrochempy/spectrochempy/discussions
    about: |
      Ask questions and discuss with other community members here.
      If you have a question like "Why when I change the units of a
      coordinates it does not work?"
      then
      please include a self-contained reproducible example if possible.
